### ISSUE TITLE
mac OSX support 

### ISSUE THREAD

**Issue by David-Melo** [microsoft/react-native#57]
- [ x] Review the documentation: https://facebook.github.io/react-native
  - [ x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
      Memory: 3.68 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.1.0 - ~/.nvm/versions/node/v11.1.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.1.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 28
        Build Tools: 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.7.0 => 16.7.0 
      react-native: Microsoft/react-native#master => 0.58.6-microsoft.31 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
Hello, I'm trying to integrate this react-native into an existing empty macOs app using cocoapods. I'm receiving the following error: 

"[!] The platform of the target `my-react-xp-app` (macOS 10.14) is not compatible with `React/Core (0.58.6-microsoft.31)`, which does not support `osx`."

Is macos supported on the current master branch? thanks.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by tom-un** [comment]
Hi.  Its on our radar to get cocoapods working for mac.   Right now, the mac libs have to be manually integrated into a app.   One way is to aggregate the React and other Library xcodeproj's into your xcodeproj -- like RNTester/RNTester.xcodeproj does in this repo.

**Comment by foxnoodles** [comment]
Any follow up on this? To simplify the context I'll rephrase the question:  Can we build cross-platform Win10 and Mac OS apps using the current main branch?

**Comment by alloy** [comment]
I have started work on this [here](https://github.com/microsoft/react-native/pull/211), but it thus far only targets RNTester. Having said that, it might already proof useful to you as-is.

**Comment by alloy** [comment]
Closing in favour of https://github.com/microsoft/react-native/issues/215
